server/config/routes.rb
Rails.application.routes.draw do
	root to: 'home#index'
  
  resources :providers do
  	resources :categories
  end

  resources :organisations do
  	resources :providers
  end
  

  devise_for :users
  
  get 'order', to: 'organisations#order'
  get 'home', to: 'home#home'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/app/models/organisation.rb
class Organisation < ApplicationRecord
	has_many :user_organisations
    has_many :users, through: :user_organisations	

    has_many :organisation_providers
    has_many :providers, through: :organisation_providers	
end

server/app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_organisation, only: [:show, :edit, :update, :destroy]
  before_action :set_organisation_by_session, only: [:order]


  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Organisation.all
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
  end

  # GET /organisations/new
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
  end

  # GET /organisations.order
  def order
    # organisation is set in a session var
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisations/1
  # PATCH/PUT /organisations/1.json
  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation.destroy
    respond_to do |format|
      format.html { redirect_to organisations_url, notice: 'Organisation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

    def set_organisation_by_session
      @organisation = Organisation.find(session[:organisation_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organisation_params
      params.fetch(:organisation, {})
    end
end

server/app/helpers/organisations_helper.rb
module OrganisationsHelper
end

server/app/views/organisations/_form.html.erb
<%= form_for(organisation) do |f| %>
  <% if organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
      <% organisation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/organisations/edit.html.erb
<h1>Editing Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

server/app/views/organisations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organisations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organisations.each do |organisation| %>
      <tr>
        <td><%= link_to 'Show', organisation %></td>
        <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
        <td><%= link_to 'Destroy', organisation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organisation', new_organisation_path %>

server/app/views/organisations/new.html.erb
<h1>New Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Back', organisations_path %>

server/app/views/organisations/order.html.erb
<p id="notice"><%= notice %></p>

<% @organisation.providers.each do |provider| %>
	<%= provider.name %>
<% end %>

<%= link_to 'Back', organisations_path %>

server/app/views/organisations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<%= link_to 'Back', organisations_path %>