server/config/routes.rb
Rails.application.routes.draw do
	root to: 'home#index'
  
  resources :providers do
  	resources :categories
  end

  resources :organisations do
  	resources :providers
  end
  

  devise_for :users
  
  get 'order', to: 'organisations#order'
  get 'home', to: 'home#home'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/app/models/category.rb
class Category < ApplicationRecord
  belongs_to :provider
end

server/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_provider_access
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = @provider.categories.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = @provider.categories.find(params[:id])
    end


    # is the user owner of the product that has been submitted?
    # keep multi tenancy in mind here!
    def ensure_provider_access
      @provider = Provider.find(params[:provider_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :provider_id)
    end
end

server/app/helpers/categories_helper.rb
module CategoriesHelper
end

server/app/views/categories/_form.html.erb
<%= form_for(@provider_category, :url => [@provider_category.provider, @provider_category]) do |f| %>

  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :provider_id %>
    <%= f.text_field :provider_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

server/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead> 
    <tr>
      <th>Name</th>
      <th>Provider</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.provider %></td>
     
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_provider_category_path %>

server/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', provider_categories_path %>

server/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @category.provider %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>